package com.eggert.engineer.task.util;

import java.util.ArrayList;
import java.util.List;

public final class CollectionUtil {

    private CollectionUtil() {}

    /**
     * Method for splitting list into sublists (generated by the help of ChatGPT, validated by unit tests that it works as expected)
     * @param list - input list
     * @param chunkSize - size of the list
     * @return - list of lists according to chunk size
     */
    public static <T> List<List<T>> batches(List<T> list, int chunkSize) {
        List<List<T>> sublists = new ArrayList<>();
        int totalSize = list.size();

        for (int i = 0; i < totalSize; i += chunkSize) {
            int end = Math.min(totalSize, i + chunkSize);
            sublists.add(new ArrayList<>(list.subList(i, end)));
        }

        return sublists;
    }
}
